root@ip-172-31-42-38:~# cat nginx.yml

---
- hosts: localhost
  become: yes
  tasks:

    - name: update
      apt: update_cache=yes

    - name: Install Nginx
      apt: name=nginx state=latest


      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      service: name=nginx state=reloaded
